'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const base=path.resolve(__dirname,'..');
vm.runInThisContext(fs.readFileSync(path.join(base,'vendor/qrcodegen.js'),'utf8'));
vm.runInThisContext(fs.readFileSync(path.join(base,'assets/core.js'),'utf8'));
const jsQR=require(path.join(base,'vendor/jsQR.js')),S=globalThis.Squares;
function image(q,patch){const scale=6,w=(q.size+8)*scale,a=new Uint8ClampedArray(w*w*4).fill(255);for(let y=0;y<q.size;y++)for(let x=0;x<q.size;x++){if(!q.getModule(x,y)||patch&&x>=patch.x&&x<patch.x+patch.n&&y>=patch.y&&y<patch.y+patch.n)continue;for(let dy=0;dy<scale;dy++)for(let dx=0;dx<scale;dx++){const i=(((y+4)*scale+dy)*w+(x+4)*scale+dx)*4;a[i]=a[i+1]=a[i+2]=0;}}return {a,w};}
function decode(q,patch){const {a,w}=image(q,patch);return jsQR(a,w,w)?.data;}
test('ordinary text, URLs, numeric data, and Unicode really decode',()=>{for(const s of ['Hello, curious human!','https://example.com/a?b=1','01234567890123456789','HELLO WORLD','Hello 🌍 · こんにちは · مرحبا'])for(const ecc of ['L','M','Q','H'])assert.equal(decode(S.qr(s,ecc)),s);});
test('all masks preserve the same Unicode message',()=>{for(let m=0;m<8;m++)assert.equal(decode(S.qr('A secret? No, just encoding 🌍','M',m)),'A secret? No, just encoding 🌍');});
test('function mask has finder/timing/payload regions and does not alter code',()=>{for(const text of ['Hi','x'.repeat(500)]){const q=S.qr(text),before=JSON.stringify(q.modules),f=S.functionMap(q);assert.equal(f.length,q.size);assert.equal(S.kind(0,0,q,f),'finder');assert.equal(S.kind(12,6,q,f),'timing');assert.ok(f.flat().some(x=>!x));assert.equal(JSON.stringify(q.modules),before);assert.equal(decode(q),text);}});
test('small central damage can recover; finder destruction can fail',()=>{const text='Damage trial: which parts matter?',q=S.qr(text,'H');assert.equal(decode(q,{x:Math.floor(q.size/2),y:Math.floor(q.size/2),n:2}),text);assert.notEqual(decode(q,{x:0,y:0,n:12}),text);});
test('UTF-8 byte accounting and base64url preserve bytes',()=>{assert.equal(S.bytes('A').length,1);assert.equal(S.bytes('🌍').length,4);const a=Uint8Array.from({length:256},(_,i)=>i);assert.deepEqual(S.unb64(S.b64(a)),a);assert.throws(()=>S.unb64('!'),/Invalid/);});
test('URL preview distinguishes host, path, and non-web schemes',()=>{assert.equal(S.inspect('https://example.com/google.com').host,'example.com');assert.equal(S.inspect('javascript:alert(1)').url,null);assert.equal(S.inspect('ordinary message').type,'Text');});
test('shared-key encryption round trip; QR holds ciphertext, never the key',async()=>{const t='Meet at the telescope 🌙',r=await S.seal(t);assert.equal(await S.open(r.envelope,r.key),t);assert.ok(!r.envelope.includes(r.key));assert.equal(decode(S.qr(r.envelope)),r.envelope);const other=await S.seal(t);assert.notEqual(r.envelope,other.envelope);await assert.rejects(()=>S.open(r.envelope,other.key));});
test('changed encrypted bytes are rejected without plaintext',async()=>{const r=await S.seal('invented practice message'),p=JSON.parse(r.envelope.slice(5)),c=S.unb64(p.c);c[0]^=1;p.c=S.b64(c);await assert.rejects(()=>S.open('SSQ1:'+JSON.stringify(p),r.key));});
test('public-key hybrid exchange survives key export/import and QR',async()=>{const p=await S.keys(),pub=await S.publicExport(p.publicKey),priv=await S.privateExport(p.privateKey),r=await S.seal('Only the receiving key unlocks this.',null,await S.publicImport(pub));assert.equal(await S.open(r.envelope,'',await S.privateImport(priv)),'Only the receiving key unlocks this.');assert.equal(decode(S.qr(pub)),pub);assert.equal(decode(S.qr(r.envelope)),r.envelope);await assert.rejects(()=>S.open(r.envelope,'',null));});
test('long message, reversed packets, duplicate, and split emoji round trip',async()=>{const t='🌍abc'.repeat(100),p=await S.packets(t);assert.ok(p.length>1);assert.equal(await S.assemble([...p.slice().reverse(),p[0]].join('\n')),t);for(const line of p)assert.equal(decode(S.qr(line)),line);});
test('missing, conflicting, mixed, and changed packets are rejected',async()=>{const p=await S.packets('a'.repeat(500));await assert.rejects(()=>S.assemble(p.slice(1).join('\n')),/Missing/);const changed=JSON.parse(p[0].slice(5));changed.b=S.b64(S.bytes('changed'));await assert.rejects(()=>S.assemble([...p,'SSP1:'+JSON.stringify(changed)].join('\n')),/Conflicting/);await assert.rejects(()=>S.assemble(['SSP1:'+JSON.stringify(changed),...p.slice(1)].join('\n')),/Checksum/);const q=await S.packets('another message');await assert.rejects(()=>S.assemble([...p,q[0]].join('\n')),/different/);});
test('empty packet transfer and size limits',async()=>{assert.equal(await S.assemble((await S.packets('')).join('\n')),'');await assert.rejects(()=>S.packets('a'.repeat(4097)),/4096/);await assert.rejects(()=>S.assemble('not a packet'),/SSP1/);assert.throws(()=>S.qr('x'.repeat(5000),'H'));});
